### ISSUE TITLE
Python Language Server CPU usage 100%

### ISSUE THREAD

**Issue by sneridagh** [palantir/python-language-server#421]
<img width="492" alt="screen shot 2018-09-13 at 10 46 53" src="https://user-images.githubusercontent.com/486927/45477788-9b896f00-b742-11e8-8e55-54fca514e4c8.png">

I have to manage a very large Python codebase, but this is ridiculous... It doesn't calm at any time.

**Comment by gatesn** [comment]
Which version are you running? We had an issue recently where the language server went into a recursive loop.

**Comment by sneridagh** [comment]
It's on VSCode: See https://github.com/Microsoft/vscode-python/issues/2297

**Comment by srosti** [comment]
I saw the same thing until I pointed vscode to the correct python interpreter.
[https://code.visualstudio.com/docs/python/environments](url)

**Comment by gatesn** [comment]
This should be fixed with an upgraded Jedi. Please re-open if not

**Comment by ahmed-shariff** [comment]
Upgraded to jedi-0.13.3, and I am still getting 100% cpu usage and pyls frequently hangs to the point where I have to manually kill the pyls process to be able to edit anything. any suggestions to fix this?

I am using emacs and lsp-mode

**Comment by arkhan** [comment]
I have the same issue
Please help!!

**Comment by vlurgio** [comment]
Same issue here and can't figure out what's happening

**Comment by c0deaddict** [comment]
I'm also having this issue, it seems to be triggered when I start a string or edit a comment. The only solution seems to be to kill the pyls process.

When I do a `strace -p $(pgrep pyls)` I see pyls `stat` and `lstat`-ing all the files in the workspace, continuously repeating.

edit: on latest version (0.27.0) and using Jedi 0.13.3

**Comment by noobymcnoob** [comment]
I had this issue with Emacs and the fix was to remove a bunch of folders from the workspace.

**Comment by srj-github** [comment]
I'm also using emacs with pyls and this issue is starting to bug me. Can you please be more specific as to which folders were removed to fix the issue?

**Comment by noobymcnoob** [comment]
Your own folders

**Comment by srj-github** [comment]
If you are referring to the folder in which my project files are, I only have a single file "main.py" in there. So I guess it's another issue on my end :(

**Comment by Mic92** [comment]
I suspect that the problem with emacs-lsp is different from original bug reported here. Maybe we should open a new ticket. However so far I have not figured out when it triggers.

**Comment by srj-github** [comment]
I have fixed my issue but, sadly, I don't remember exactly how. It was surely a missing package that solved it, but I don't know which. Might be the emacs package "company-jedi" or "jedi" from pip but I'm not sure right now.

**Comment by mgax** [comment]
FWIW, I had the same problem, with a large virtualenv installed inside the project directory. Moving the virtualenv outside the project root solved the issue, the language server is very snappy now.
